name: flutter_demo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  delightful_toast: ^1.1.0
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_map: ^7.0.2
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  camera: ^0.10.5+9
  encrypt: ^5.0.3
  sqflite: ^2.0.0+4
  syncfusion_flutter_pdf: ^21.2.4
  path_provider: ^2.0.11
  open_file: ^3.2.1
  flutter_offline: ^4.0.0
  internet_connection_checker: ^3.0.1
  device_info_plus: ^11.2.1
  android_id: ^0.4.0
  fluttertoast: ^8.0.9
  connectivity_plus: ^6.1.1  # Upgrade this to a compatible version
  crypto: ^3.0.1
  path: ^1.9.0
  logger: ^2.5.0
  uuid: ^4.5.1
  idb_shim: ^2.6.1+7
  universal_html: ^2.2.4
  file_picker: ^8.3.5


  flutter_localizations:
    sdk: flutter
  # flutter_gen: ^5.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Regular.ttf
         - asset: assets/fonts/Montserrat-Bold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
           weight: 700
